src/server.ts
src/util/helpers.ts

- Filters doctors by the type of appointment available

feat: adds a new filter for /doctors

---

DATA.md
scripts/archiveAppointments.ts

- This script updates the coreAppointment status in MongoDB doucments. Now it is set to 2h

fix: Updating time for archiveAppointment script

---

src/util/helpers.ts

+ Method for querying in mongo was without the line that searched in "fridays"

fix: bug in doctors filter

---

src/server.ts

Add endpoints for identification and extraction personal data from patient document

verify identity with id card paraguay for dependent patient

---

src/server.ts

- add endpoints for create and list appointments

Module my family

---

Dockerfile

- Endpoints  for managing caretakers of a dependent
- Endpoints for managing diagnostic reports

My managers and my medical studies

---

src/server.ts

Delete endpoint /medications of open access

Protect medications endpoint

---

src/server.ts

Remove res.send when ServiceRequest service fails

My medical studies

---

src/scripts/archiveAppointments.ts
src/scripts/info.md
src/server.ts

+ It is possible to invoque an endpoint for the /script/archiveAppointment

feat: archiveAppointment available for endpoint invocation

---

scripts/archiveAppointments.ts
src/scripts/info.md
src/server.ts

Reverts iHub-PTI/boldo-server#73

Revert "feat: archiveAppointment available for endpoint invocation"

---

src/server.ts
src/util/helpers.ts

Two enviroment variables are added:
- APPOINTMENT_LENGTH: indicates duration of appointments
- APPOINTMENT_WAIT_RESERVATION_LENGTH: indicates the minimum previous time in which an available appointment can be scheduled (the maximum is APPOINTMENT_LENGTH)

enviroment variables are added for appointments

---

src/server.ts
src/util/helpers.ts

- add endpoint to create patient diagnostic report from a doctor profile.
- add endpoint to synchronize farmanuario medications from admin profile

Add new endpoints for create diagnostic reports from doctor profile and execute farmanuario synchro from admin profile

---

src/server.ts

+ GET /profile/doctor/appointments/:id/encounter/prescription/pdf
+ GET /reports/:report_identifier

feat: endpoints for Prescriptions creation added

---

src/server.ts

- Add endpoints for get all encounters by patientId and encounter detail by id

Ambulatory record

---

src/server.ts

+ Path corrected in new endpoint with /profile/doctor
+ bug fixed in old endpoints when catching errors in try catch block
+ previous endpoints are deprecated, and new endpoints must be updated in clients

fix: new endpoints updated for patient management

---

src/server.ts
src/types/iHub.d.ts

Change profile from public to patient for endpoints of get doctors
Calculate next availability for each workspace in get doctors

Availability of doctors by blocks

---

src/server.ts
src/types/iHub.d.ts

Add organization ids in the appointment and coreappointment collection filter, to get appointment reservations from a doctor.

Availability of doctor

---

src/server.ts

Get the list of organizations for the doctor when the organizationId parameter is not passed

Doctor availabilities

---

src/server.ts

Add filter for private notes from a doctor in the ambulatory record service

Filter private notes in ambularoty record

---

src/server.ts

+ Query param "reports" now is valid for single and multiple arrays
+ Reponse code is sent to client

fix: Endpoint for printing PDF reports updated for /profile/doctor

---

src/server.ts

- Add openHours settings overlay control between appointment type

openHours settings in the doctor profile

---

src/server.ts

+ POST /profile/doctor/condition to create a new record of a detected patient pathology
+ DELETE /profile/doctor/condition to delete a record of patient pathology

feat: endpoints for management of pathologies in patient's history

---

src/server.ts
src/util/helpers.ts

- Add service to get doctor availability for dependent patient profile
- Add the service to get a list of doctors with common organizations for a dependent patient
- organizationList field is changed to optional in a doctor availability service
- Add the organization name field in the return of a doctor's availability service

BMO - dependent patient profile

---

src/server.ts

+ add endpoint PUT /profile/doctor/procedure/:id to performs an update on a patient's procedure corresponding to a logical deletion due to status update

feat: logical deletion of patient procedures

---

src/server.ts

Feat: new service is added to get the last appointment of a patient with a doctor

Last encounter of a patient with a doctor

---

src/server.ts

+ Feat: service is added to obtain the last appointment of a dependent with a doctor
profile/patient
+ feat: Added parameter to control the inclusion of dependent patients

Generalization of the last encounter service

---

Dockerfile

**New service:** Last encounter of a patient with a doctor

Merge test into main: PROD deployment

---

src/server.ts

+feat: function is added to obtain the favorite doctors of a patient
+feat: add feature to bookmark and unmark a doctor
+fix: Correction in the sending of the body in the call PUT.

Favorite doctor

---

src/server.ts

+feat: service is added that retrieves the list of doctors, according to the last consultations of the patient, in a range of one month to date.
+ fix: Return status control

Recent doctors

---

src/server.ts

+ description: filter for study description
+ withOrder: boolean filter to obtain studies with or without order
+ newFirst: boolean param to select the order of studies by date in ascending or descending order
+ currentDoctorOnly: to obtain studies authored by the current doctor

set: add filters in GET /profile/doctor/studies

---

src/server.ts

+ feat: Consultation service of recent doctors of dependent patients …is added
+ feat: Service for adding/removing doctors as favorites for dependent patients is added
+feat: Consultation service of favorite doctors of dependent patients is added

Favorite recent for dependents

---

src/server.ts

Makes some organization-manager profile endpoint's available for client. Related to https://github.com/iHub-PTI/core-health-mapper/pull/211

feat: Organization manager PUT organizations & organizations settings

---

Dockerfile
package.json
src/server.ts

- fix: Correction in the sending of the body in the call PUT.
- feat: add filter for study order number in serviceRequests get method
- Fit: add filters in service to get recent doctors
- feat: add endpoint for order and study results
- Fit: unify method of calculating the next availability of a doctor
- feat: Service for adding/removing doctors as favorites for dependent patients is added
- feat: Consultation service of favorite doctors of dependent patients is added
- description: filter for study description
- withOrder: boolean filter to obtain studies with or without order
- newFirst: boolean param to select the order of studies by date in ascending or descending order
- currentDoctorOnly: to obtain studies authored by the current doctor
- feat: Organization manager PUT organizations …

Merge dev into test: TEST deployment 

---

src/util/helpers.ts

+ fix: set the total of results in Doctors With Availability

Set total results

---

src/server.ts

+ It requests endpoint that queries the elasticSearch instance

feat: endpoint for filter encounters from patient

---

src/server.ts
src/util/helpers.ts

+ fix: set the total of results in Doctors With Availability
+ feat: endpoint for filter encounters from patient 
+ fix: update in object for file upload
+ fix:set toString presigned

Merge dev into test
